version: '3.8'

services:
  web:
    build: .
    image: wahlfernando/desafiogo
    container_name: desafiogo
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./hello.go -b 0.0.0.0
